version: "3"

services:
  db:
    image: postgres:13
    container_name: wiki-mx-db
    restart: always
    environment:
      POSTGRES_DB: wiki_mx_db
      POSTGRES_USER: wiki_mx_user
      POSTGRES_PASSWORD: wiki_mx_pass
    volumes:
      - wiki-mx-db:/var/lib/postgresql/data

  wikijs:
    image: requarks/wiki:2
    container_name: mx-wikijs
    restart: always
    ports:
      - "3002:3000"
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wiki_mx_user
      DB_PASS: wiki_mx_pass
      DB_NAME: wiki_mx_db
    depends_on:
      - db
    volumes:
      - wiki-mx-data:/wiki/data

volumes:
  wiki-mx-db:
  wiki-mx-data:
